CREATE TABLE oldemp ( 
  fname char(25), lname CHAR(25))
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_LOADER
  DEFAULT DIRECTORY emp_dir
  ACCESS PARAMETERS
  (RECORDS DELIMITED BY NEWLINE
   NOBADFILE 
   NOLOGFILE 
  FIELDS TERMINATED BY ',' 
  (fname POSITION ( 1:20) CHAR,
   lname POSITION (22:41) CHAR))
  LOCATION ('emp.dat'))
  PARALLEL 5
  REJECT LIMIT 200;




--CREATE OR REPLACE DIRECTORY emp_dir 
--AS '/…/emp_dir'; 


--GRANT READ ON DIRECTORY emp_dir TO hr