SELECT DB_NAME,LOG_ARCHIVED, LOG_APPLIED,LOG_ARCHIVED-LOG_APPLIED LOG_GAP
FROM 
(
SELECT INSTANCE_NAME DB_NAME, THREAD# FROM GV$INSTANCE
) A,
(
SELECT MAX(SEQUENCE#) LOG_ARCHIVED, THREAD# FROM V$ARCHIVED_LOG 
WHERE STANDBY_DEST='NO' AND ARCHIVED='YES'
GROUP BY THREAD#
) B,
(
SELECT MAX(SEQUENCE#) LOG_APPLIED, THREAD# FROM V$ARCHIVED_LOG
WHERE STANDBY_DEST='YES' AND APPLIED='YES'
GROUP BY THREAD#
) C
WHERE A.THREAD#=B.THREAD# 
AND B.THREAD#=C.THREAD#;